name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: unbuntu-lastest
    steps:
      - name: Checkout code
        uses: actions/checkou@v2
        
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
